apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xpto-info
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        prefix: /login
    route:
    - destination:
        port:
          number: 80
        host: xptopage
